### ISSUE TITLE
settings.py missing

### ISSUE THREAD

**Issue by alex37529** [ImaginaryLandscape/multipage-form-demo#5]
Зачем в .gitignore внес settings.py ???
Без него проект бесполезен.

**Comment by 326926d** [comment]
> Зачем в .gitignore внес settings.py ???
> Без него проект бесполезен.

Лучше по-английски:
why did you insert settings.py into the gitignore..?!?!

**Comment by xtiansimon** [comment]
Hey peeps. I had the same issue, but thankfully it's easily resolved.
1. Create your virtual environment
2. Create a new project: `django-admin startproject multipage_form_demo .`
3. Copy files and folders from cloned repo into new project.
4.  Add to `INSTALLED_APPS = ['job_application.apps.JobApplicationConfig', ....]`

That's all it took for me to get the example working.
